### ISSUE TITLE
Add Issue and Contribution Template

### ISSUE THREAD

**Issue by therajanmaurya** [therajanmaurya/Stock-Hawk#24]
Now project does not have any guidelines for opening Issue and for making a #PR.

So, Add Issue and Contribution Template

**Comment by aaabramov** [comment]
Hi @therajanmaurya. I can take of this.

You an assign this to me and we сan discuss the requirements.

**Comment by therajanmaurya** [comment]
@Abrasha welcome.

**Comment by therajanmaurya** [comment]
Add #37
