### ISSUE TITLE
Add Documentation.

### ISSUE THREAD

**Issue by therajanmaurya** [therajanmaurya/Stock-Hawk#31]
Add documentation, So that any contributor can contribute easily and write quality code in his #PR

**Comment by MoriTanosuke** [comment]
Hey @therajanmaurya , I'd like to help out. Do you have any specific information or is a more general `CONTRIBUTING.md` file acceptable?

I'd start with https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines and create a pull request then.

**Comment by therajanmaurya** [comment]
@MoriTanosuke Yeah, write a general contribution guideline and send a PR.

**Comment by therajanmaurya** [comment]
Add in #38
